jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        name: "Thomas Holmes"